# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      KEY: ${{ secrets.WEB_HOOK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Deploy
        run: mvn -B test --file pom.xml && curl http://106.15.205.190:2271/hook?access_key=$KEY
